version: "2.3"

services:
  sam:
    runtime: nvidia
    userns_mode: "host"
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    working_dir: /workspace
    image: ${USER}-sam-gpu:v1
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        - OUTSIDE_USER=${USER}
        - OUTSIDE_UID=${OUTSIDE_UID}
        - OUTSIDE_GROUP=${OUTSIDE_GROUP}
        - OUTSIDE_GID=${OUTSIDE_GID}
    volumes:
      - type: bind
        source: /work/${USER}/Exp
        target: /Exp
      - type: bind
        source: /work/${USER}/DL
        target: /DL
      - type: bind
        source: /work/${USER}/sam
        target: /workspace
      - type: bind
        source: /work/${USER}/container_home
        target: /home/${USER}
    user: ${USER}
    group_add:
      - ${OUTSIDE_GROUP}
    environment:
      - TFHUB_CACHE_DIR=/home/${USER}/tfhub_modules

